### ISSUE TITLE
Add contributing template

### ISSUE THREAD

**Issue by devthepenguin** [Abhishek-kumar09/AutoBot#29]
A contrib guideline can look something similar to the one described below:

### Title

That's right, a simple description for issue/pr can go here

### description

Oh! Love the descriptions.

### Solution

Appropriate workaorunds.

**Comment by rashi-s17** [comment]
Hey @devthepenguin! Can I take up this issue?

**Comment by devthepenguin** [comment]
Sure @rashi-s17 go ahead!!
